version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
      target: dev
    volumes:
      - ./src:/src
    command: npm run watch
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: dev