version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
      target: dev
    container_name: nodeweb_web
    volumes:
      - ./src:/src
      - /src/node_modules
    command: npm run watch
    ports:
      - "10004:3000"
    depends_on:
      - "mysql"
    environment:
      NODE_ENV: development
    networks:
      - backend
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: nodeweb_mysql
    restart: always
    ports:
      - "3333:3306"
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d
      - nodeweb_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nodeweb_myadmin
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - .docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - .docker/phpmyadmin/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 10005:80
    depends_on:
      - "mysql"
    networks:
      - backend
networks:
  backend:
volumes:
  nodeweb_data:
    external: true